export type NewsCategory = 'crypto' | 'macro' | 'regulation' | 'onchain' | 'markets';
export type Impact = 1 | 2 | 3; // low · medium · high

export interface NewsStory {
  id: string;
  time: number;
  source: string;
  category: NewsCategory;
  /** Asset symbols the story is about (may be empty for macro). */
  symbols: string[];
  headline: string;
  summary?: string;
  impact: Impact;
  /** −1 bearish · 0 neutral · +1 bullish for the tagged assets. Heuristic, not advice. */
  sentiment: -1 | 0 | 1;
  url?: string;
  /** Set when the story was generated by a calendar release. */
  eventId?: string;
}

export type Region = 'US' | 'EU' | 'UK' | 'JP' | 'CN' | 'CA' | 'AU' | 'CRYPTO';

export interface EconEvent {
  id: string;
  time: number;
  region: Region;
  title: string;
  impact: Impact;
  kind: 'macro' | 'crypto';
  unit?: string;
  decimals?: number;
  forecast?: number;
  previous?: number;
  actual?: number;
  /** Whether a print above forecast is good for the region's currency / risk (e.g. false for unemployment). */
  higherIsBetter?: boolean;
  /** Free-text detail for non-numeric events (unlocks, expiries, upgrades). */
  detail?: string;
}

export interface NewsHandlers {
  onStories: (s: NewsStory[]) => void;
  onCalendar: (events: EconEvent[]) => void;
  onEventUpdate: (e: EconEvent) => void;
}

/**
 * Source seam, mirroring MarketDataProvider. The mock generates a realistic wire + calendar locally.
 * A production adapter would subscribe to a licensed headline socket and a calendar API (see README).
 */
export interface NewsProvider {
  id: string;
  label: string;
  start: (h: NewsHandlers) => () => void;
}

/** Surprise vs forecast: +1 better than expected, −1 worse, 0 in line / n.a. */
export function surprise(e: EconEvent): -1 | 0 | 1 {
  if (e.actual == null || e.forecast == null) return 0;
  const d = e.actual - e.forecast;
  if (Math.abs(d) < 10 ** -((e.decimals ?? 1) + 1)) return 0;
  const up = d > 0 ? 1 : -1;
  return (e.higherIsBetter === false ? -up : up) as -1 | 1;
}

export function fmtEventValue(e: EconEvent, v: number | undefined): string {
  if (v == null) return '—';
  const s = v.toFixed(e.decimals ?? 1);
  return e.unit === '%' ? `${s}%` : e.unit ? `${s}${e.unit}` : s;
}
